Update cd.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -22,28 +22,49 @@ jobs:
       AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
 
     steps:
-      - name: Get environment variable from aws ssm
-        uses: Bardavon-Health/actions-aws-ssm-params-to-env@v1.2
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
+      - name: Set up AWS CLI
+        uses: aws-actions/configure-aws-credentials@v1
         with:
-          ssm-path: /${{ env.BUILD_STAGE }}/${{ env.BUILD_APP }}/test
-          prefix: null
-          decryption: true
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+
+      - name: Create CloudWatch Event Rule
+        run: |
+          aws events put-rule --name "ScheduledCleanupRule" \
+            --schedule-expression "rate(1 hour)"
+
+      - name: Add Lambda Target to the Rule
+        run: |
+          aws events put-targets --rule "ScheduledCleanupRule" \
+            --targets "Id"="1","Arn"=${{ vars.AWS_EBS_ENV_CLEANUP_LAMBDA_FUNCTION_ARN }}
+
+      - name: Enable Rule
+        run: |
+          aws events enable-rule --name "ScheduledCleanupRule"
+
+      # - name: Get environment variable from aws ssm
+      #   uses: Bardavon-Health/actions-aws-ssm-params-to-env@v1.2
+      #   env:
+      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      #     AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
+      #   with:
+      #     ssm-path: /${{ env.BUILD_STAGE }}/${{ env.BUILD_APP }}/test
+      #     prefix: null
+      #     decryption: true
           
-      - name: Output Bardavon Actions
-        env:
-          CNAME: ${{ env.AWS_DEFAULT_REGION }}
-        run: | 
-          echo "$CNAME"
-          echo ${{ env.AWS_DEFAULT_REGION }}
-          if [ ${{ env.AWS_DEFAULT_REGION }} = ap-southeast-1 ]; then
-            echo "true"
-          else
-            echo "false"
-          fi
+      # - name: Output Bardavon Actions
+      #   env:
+      #     CNAME: ${{ env.AWS_DEFAULT_REGION }}
+      #   run: | 
+      #     echo "$CNAME"
+      #     echo ${{ env.AWS_DEFAULT_REGION }}
+      #     if [ ${{ env.AWS_DEFAULT_REGION }} = ap-southeast-1 ]; then
+      #       echo "true"
+      #     else
+      #       echo "false"
+      #     fi
 
       # - name: Parse and set environment variables
       #   run: |
@@ -74,30 +95,30 @@ jobs:
       #     name: env-file
       #     path: .env
       
-      - name: Install EB CLI using pip
-        run: |
-          python -m pip install --upgrade pip
-          pip install awsebcli
+      # - name: Install EB CLI using pip
+      #   run: |
+      #     python -m pip install --upgrade pip
+      #     pip install awsebcli
 
-      - name: Initialize EB CLI
-        run: |
-          eb init ${{ env.AWS_EBS_APPLICATION }} --region ${{ env.AWS_DEFAULT_REGION }} --platform ${{ env.AWS_EBS_PLATFORM }}
-          eb use ${{ env.AWS_EBS_ENVIRONMENT }}
+      # - name: Initialize EB CLI
+      #   run: |
+      #     eb init ${{ env.AWS_EBS_APPLICATION }} --region ${{ env.AWS_DEFAULT_REGION }} --platform ${{ env.AWS_EBS_PLATFORM }}
+      #     eb use ${{ env.AWS_EBS_ENVIRONMENT }}
 
-      - name: Get Elastic Beanstalk blue environment name
-        id: target-blue-env
-        run: |
-          for ebs_env in $(eb list | awk '{print $1}'); do
-            ebs_env_cname=$(eb status $ebs_env | grep "CNAME:" | awk '{print $2}')
-            [ "$ebs_env_cname" = ${{ env.CNAME }} ] && blue_env_name="$ebs_env" >> $GITHUB_OUTPUT
-          done
+      # - name: Get Elastic Beanstalk blue environment name
+      #   id: target-blue-env
+      #   run: |
+      #     for ebs_env in $(eb list | awk '{print $1}'); do
+      #       ebs_env_cname=$(eb status $ebs_env | grep "CNAME:" | awk '{print $2}')
+      #       [ "$ebs_env_cname" = ${{ env.CNAME }} ] && blue_env_name="$ebs_env" >> $GITHUB_OUTPUT
+      #     done
 
-          if [ -n "$blue_env_name" ]; then
-            echo "Blue environment found: $blue_env_name"
-          else
-            echo "Elastic Beanstalk blue environment for: ${{ env.NODE_ENV }} not found"
-            exit 1
-          fi
+      #     if [ -n "$blue_env_name" ]; then
+      #       echo "Blue environment found: $blue_env_name"
+      #     else
+      #       echo "Elastic Beanstalk blue environment for: ${{ env.NODE_ENV }} not found"
+      #       exit 1
+      #     fi
 
       # - name: Get Elastic Beanstalk blue environment name
       #   id: target-blue-env
