Update cd.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -75,91 +75,91 @@ jobs:
       #     name: env-file
       #     path: .env
       
-      - name: Create .env file
-        uses: SpicyPizza/create-envfile@v2.0
-        with:
-          envkey_ID_DATABASE_URL: ${{ env.ID_DATABASE_URL }}
-          envkey_KR_DATABASE_URL: ${{ env.KR_DATABASE_URL }}
-          envkey_MASTER_DATABASE_URL: ${{ env.MASTER_DATABASE_URL }}
-          REDIS_DOMAIN: ${{ env.REDIS_DOMAIN }}
-          envkey_REDIS_PORT_NUMBER: ${{ env.REDIS_PORT_NUMBER }}
-          envkey_REDIS_CLUSTER_PASSWORD: ${{ env.REDIS_CLUSTER_PASSWORD }}
-          envkey_GCP_SERVICE_ACCOUNT: ${{ env.GCP_SERVICE_ACCOUNT }}
-          envkey_SERVER_DOMAIN: ${{ env.SERVER_DOMAIN }}
-          envkey_DOMAIN: ${{ env.DOMAIN }}
-          envkey_FIREBASE_API_KEY: ${{ env.FIREBASE_API_KEY }}
-          envkey_SENDGRID_API_KEY: ${{ env.SENDGRID_API_KEY }}
-          envkey_ENCRYPT_KEY: ${{ env.ENCRYPT_KEY }}
-          envkey_ENCRYPT_IVS: ${{ env.ENCRYPT_IVS }}
-          envkey_SENTRY_DSN: ${{ env.SENTRY_DSN }}
-          envkey_GOOGLE_CLIENT_ID: ${{ env.GOOGLE_CLIENT_ID }}
-          envkey_ENVIRONMENT: ${{ env.ENVIRONMENT }}
-          envkey_NODE_ENV: ${{ env.NODE_ENV }}
-          # TODO: Retrieve API KEYS JSON from the SSM for dynamic configuration.
-          # Note: Bardavon-Health/actions-aws-ssm-params-to-env@v1.2 currently does not handle nested JSON properties properly,
-          # causing formatting issues, investigate this further to use keys from SSM.
-          envkey_API_KEYS_JSON: '{
-            "INGENICO_API_KEY":"ingenico_testapikey",
-            "FMI_API_KEY":"fmi_testapikey",
-            "MOCKPOS_API_KEY":"mockpos_testapikey",
-            "DEMO_PRINT_DRIVER_COMPANY":"demoprintdriver_testapikey",
-            "KOOMI_API_KEY":"koomi_testapikey",
-            "PAX_TERMINAL_DEMO_API_KEY":"paxterminal_testapikey"
-            }'
-          envkey_JWT_EXPIRY: ${{ env.JWT_EXPIRY }}
-          envkey_JWT_SECRET: ${{ env.JWT_SECRET }}
-          envkey_JWT_AUDIENCE: ${{ env.JWT_AUDIENCE }}
-          envkey_JWT_PROVIDER: ${{ env.JWT_PROVIDER }}
-          envkey_TEST_ACCOUNT_UID: test
-          envkey_LINE_CLIENT_ID: ${{ env.LINE_CLIENT_ID }}
-          envkey_LINE_CLIENT_SECRET: ${{ env.LINE_CLIENT_SECRET }}
-          envkey_SANDBOX_MODE: ${{ env.SANDBOX_MODE }}
-          envkey_DEMO_MODE: ${{ env.DEMO_MODE }}
-          envkey_PLAYGROUND: ${{ env.PLAYGROUND }}
-          envkey_API_DOCS_PATH: ${{ env.API_DOCS_PATH }}
-          fail_on_empty: true
+      # - name: Create .env file
+      #   uses: SpicyPizza/create-envfile@v2.0
+      #   with:
+      #     envkey_ID_DATABASE_URL: ${{ env.ID_DATABASE_URL }}
+      #     envkey_KR_DATABASE_URL: ${{ env.KR_DATABASE_URL }}
+      #     envkey_MASTER_DATABASE_URL: ${{ env.MASTER_DATABASE_URL }}
+      #     REDIS_DOMAIN: ${{ env.REDIS_DOMAIN }}
+      #     envkey_REDIS_PORT_NUMBER: ${{ env.REDIS_PORT_NUMBER }}
+      #     envkey_REDIS_CLUSTER_PASSWORD: ${{ env.REDIS_CLUSTER_PASSWORD }}
+      #     envkey_GCP_SERVICE_ACCOUNT: ${{ env.GCP_SERVICE_ACCOUNT }}
+      #     envkey_SERVER_DOMAIN: ${{ env.SERVER_DOMAIN }}
+      #     envkey_DOMAIN: ${{ env.DOMAIN }}
+      #     envkey_FIREBASE_API_KEY: ${{ env.FIREBASE_API_KEY }}
+      #     envkey_SENDGRID_API_KEY: ${{ env.SENDGRID_API_KEY }}
+      #     envkey_ENCRYPT_KEY: ${{ env.ENCRYPT_KEY }}
+      #     envkey_ENCRYPT_IVS: ${{ env.ENCRYPT_IVS }}
+      #     envkey_SENTRY_DSN: ${{ env.SENTRY_DSN }}
+      #     envkey_GOOGLE_CLIENT_ID: ${{ env.GOOGLE_CLIENT_ID }}
+      #     envkey_ENVIRONMENT: ${{ env.ENVIRONMENT }}
+      #     envkey_NODE_ENV: ${{ env.NODE_ENV }}
+      #     # TODO: Retrieve API KEYS JSON from the SSM for dynamic configuration.
+      #     # Note: Bardavon-Health/actions-aws-ssm-params-to-env@v1.2 currently does not handle nested JSON properties properly,
+      #     # causing formatting issues, investigate this further to use keys from SSM.
+      #     envkey_API_KEYS_JSON: '{
+      #       "INGENICO_API_KEY":"ingenico_testapikey",
+      #       "FMI_API_KEY":"fmi_testapikey",
+      #       "MOCKPOS_API_KEY":"mockpos_testapikey",
+      #       "DEMO_PRINT_DRIVER_COMPANY":"demoprintdriver_testapikey",
+      #       "KOOMI_API_KEY":"koomi_testapikey",
+      #       "PAX_TERMINAL_DEMO_API_KEY":"paxterminal_testapikey"
+      #       }'
+      #     envkey_JWT_EXPIRY: ${{ env.JWT_EXPIRY }}
+      #     envkey_JWT_SECRET: ${{ env.JWT_SECRET }}
+      #     envkey_JWT_AUDIENCE: ${{ env.JWT_AUDIENCE }}
+      #     envkey_JWT_PROVIDER: ${{ env.JWT_PROVIDER }}
+      #     envkey_TEST_ACCOUNT_UID: test
+      #     envkey_LINE_CLIENT_ID: ${{ env.LINE_CLIENT_ID }}
+      #     envkey_LINE_CLIENT_SECRET: ${{ env.LINE_CLIENT_SECRET }}
+      #     envkey_SANDBOX_MODE: ${{ env.SANDBOX_MODE }}
+      #     envkey_DEMO_MODE: ${{ env.DEMO_MODE }}
+      #     envkey_PLAYGROUND: ${{ env.PLAYGROUND }}
+      #     envkey_API_DOCS_PATH: ${{ env.API_DOCS_PATH }}
+      #     fail_on_empty: true
 
-      - name: Install EB CLI using pip
-        run: |
-          python -m pip install --upgrade pip
-          pip install awsebcli
+      # - name: Install EB CLI using pip
+      #   run: |
+      #     python -m pip install --upgrade pip
+      #     pip install awsebcli
 
-      - name: Initialize EB CLI
-        run: |
-          eb init ${{ env.AWS_EBS_APPLICATION }} --region ${{ env.AWS_DEFAULT_REGION }} --platform ${{ env.AWS_EBS_PLATFORM }}
-          eb use ${{ env.AWS_EBS_ENVIRONMENT }}
+      # - name: Initialize EB CLI
+      #   run: |
+      #     eb init ${{ env.AWS_EBS_APPLICATION }} --region ${{ env.AWS_DEFAULT_REGION }} --platform ${{ env.AWS_EBS_PLATFORM }}
+      #     eb use ${{ env.AWS_EBS_ENVIRONMENT }}
 
-      - name: Get Elastic Beanstalk blue environment name
-        id: target-blue-env
-        run: |
-          for ebs_env in $(eb list | awk '{print $1}'); do
-            ebs_env_cname=$(eb status $ebs_env | grep "CNAME:" | awk '{print $2}')
-            echo "$ebs_env_cname"
-            echo "ebs_env" $ebs_env
-            [ "$ebs_env_cname" = ${{ env.CNAME }} ] && blue_env_name="$ebs_env" 
-          done
+      # - name: Get Elastic Beanstalk blue environment name
+      #   id: target-blue-env
+      #   run: |
+      #     for ebs_env in $(eb list | awk '{print $1}'); do
+      #       ebs_env_cname=$(eb status $ebs_env | grep "CNAME:" | awk '{print $2}')
+      #       echo "$ebs_env_cname"
+      #       echo "ebs_env" $ebs_env
+      #       [ "$ebs_env_cname" = ${{ env.CNAME }} ] && blue_env_name="$ebs_env" 
+      #     done
 
-          echo "blue_env_name=$blue_env_name" >> $GITHUB_OUTPUT
-          echo "blue_env_name:" "$blue_env_name"
-          if [ -n "$blue_env_name" ]; then
-            echo "Blue environment found: $blue_env_name"
-          else
-            echo "Elastic Beanstalk blue environment for: ${{ env.NODE_ENV }} not found"
-            exit 1
-          fi
+      #     echo "blue_env_name=$blue_env_name" >> $GITHUB_OUTPUT
+      #     echo "blue_env_name:" "$blue_env_name"
+      #     if [ -n "$blue_env_name" ]; then
+      #       echo "Blue environment found: $blue_env_name"
+      #     else
+      #       echo "Elastic Beanstalk blue environment for: ${{ env.NODE_ENV }} not found"
+      #       exit 1
+      #     fi
 
-      - name: Create and populate ebextensions security group config file
-        run: |
-          mkdir -p .ebextensions
-          cat <<EOF > .ebextensions/security-group.config
-          option_settings:
-            aws:elbv2:loadbalancer:
-              ManagedSecurityGroup: ${{ env.ELB_MANAGED_SECURITY_GROUP_ID }}
-              SecurityGroups: ${{ env.ELB_MANAGED_SECURITY_GROUP_ID }}
+      # - name: Create and populate ebextensions security group config file
+      #   run: |
+      #     mkdir -p .ebextensions
+      #     cat <<EOF > .ebextensions/security-group.config
+      #     option_settings:
+      #       aws:elbv2:loadbalancer:
+      #         ManagedSecurityGroup: ${{ env.ELB_MANAGED_SECURITY_GROUP_ID }}
+      #         SecurityGroups: ${{ env.ELB_MANAGED_SECURITY_GROUP_ID }}
 
-            aws:autoscaling:launchconfiguration:
-              SecurityGroups: ${{ env.EBS_MANAGED_SECURITY_GROUP_NAME }}
-          EOF
+      #       aws:autoscaling:launchconfiguration:
+      #         SecurityGroups: ${{ env.EBS_MANAGED_SECURITY_GROUP_NAME }}
+      #     EOF
 
       # - id: get_last_commit_hash
       #   run: | 
@@ -170,31 +170,31 @@ jobs:
       #     echo "First 8 characters of SHA: $first_eight_chars"
 
           
-      - name: Create Elastic Beanstalk green environment and deploy
-        id: target-green-env
-        run: |
-          latest_commit_sha=${{ github.event.pull_request.head.sha }}
-          green_env_name=${{ env.NODE_ENV }}-${latest_commit_sha:0:8}-${{ github.run_id }}-${{ github.run_attempt }}
-          echo "$green_env_name"
-          echo "green_env_name=$green_env_name" >> $GITHUB_OUTPUT
-          eb create "$green_env_name" --cfg ${{ env.NODE_ENV }} --sample --instance-types t2.micro,t2.small
+      # - name: Create Elastic Beanstalk green environment and deploy
+      #   id: target-green-env
+      #   run: |
+      #     latest_commit_sha=${{ github.event.pull_request.head.sha }}
+      #     green_env_name=${{ env.NODE_ENV }}-${latest_commit_sha:0:8}-${{ github.run_id }}-${{ github.run_attempt }}
+      #     echo "$green_env_name"
+      #     echo "green_env_name=$green_env_name" >> $GITHUB_OUTPUT
+      #     eb create "$green_env_name" --cfg ${{ env.NODE_ENV }} --sample --instance-types t2.micro,t2.small
 
-      - name: Print green env name
-        run: | 
-          echo "green_env_name:" ${{ steps.target-green-env.outputs.green_env_name }}
-          echo "blue_env_name:" ${{ steps.target-blue-env.outputs.blue_env_name }}
+      # - name: Print green env name
+      #   run: | 
+      #     echo "green_env_name:" ${{ steps.target-green-env.outputs.green_env_name }}
+      #     echo "blue_env_name:" ${{ steps.target-blue-env.outputs.blue_env_name }}
 
-      - name: Swap cname and switch traffic to green environment
-        run: |
-          eb swap ${{ steps.target-blue-env.outputs.blue_env_name }} --destination_name ${{ steps.target-green-env.outputs.green_env_name }}
+      # - name: Swap cname and switch traffic to green environment
+      #   run: |
+      #     eb swap ${{ steps.target-blue-env.outputs.blue_env_name }} --destination_name ${{ steps.target-green-env.outputs.green_env_name }}
 
-      - name: Terminate staging-blue environment
-        if: ${{ env.NODE_ENV == 'staging' }}
-        run: |
-          eb terminate ${{ steps.target-blue-env.outputs.blue_env_name }} --force
+      # - name: Terminate staging-blue environment
+      #   if: ${{ env.NODE_ENV == 'staging' }}
+      #   run: |
+      #     eb terminate ${{ steps.target-blue-env.outputs.blue_env_name }} --force
           
   deploy_frontend:
-    needs: build
+    # needs: build
     name: Piperks Frontend Deployment
     runs-on: ubuntu-latest
 
@@ -220,13 +220,17 @@ jobs:
           prefix: null
           decryption: true
 
-      - name: Deploy to Cloudflare Pages
-        uses: cloudflare/pages-action@v1
-        if: ${{ env.NODE_ENV != 'staging' }}
-        with:
-          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
-          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
-          projectName: ${{ env.CLOUDFLARE_PROJECT_NAME}}
-          directory: ./dist/apps/piperks
-          wranglerVersion: '3'
+      - name: Print staging env name
+        run: | 
+          echo ${{ env.NODE_ENV }}
+      
+      # - name: Deploy to Cloudflare Pages
+      #   uses: cloudflare/pages-action@v1
+      #   if: ${{ env.NODE_ENV != 'staging' }}
+      #   with:
+      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
+      #     projectName: ${{ env.CLOUDFLARE_PROJECT_NAME}}
+      #     directory: ./dist/apps/piperks
+      #     wranglerVersion: '3'
 
