Update cd.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -44,20 +44,6 @@ jobs:
           else
             echo "false"
           fi
-          
-      - name: Get Elastic Beanstalk blue environment name
-        id: target-blue-env
-        env:
-          CNAME: ${{ env.AWS_DEFAULT_REGION }}
-        run: |
-          for ebs_env in $(eb list | awk '{print $1}'); do
-            echo "$ebs_env"
-            ebs_env_cname=$(eb status $ebs_env | grep "CNAME:" | awk '{print $2}')
-            [ "$ebs_env_cname" = "$CNAME" ] && blue_env_name="$ebs_env" >> $GITHUB_OUTPUT
-          done
-
-          [ -z "$blue_env_name" ] && { echo "Elastic beanstalk blue environment not found"; exit 1; }
-
 
       # - name: Parse and set environment variables
       #   run: |
@@ -87,15 +73,29 @@ jobs:
       #   with:
       #     name: env-file
       #     path: .env
-      # - name: Install EB CLI using pip
-      #   run: |
-      #     python -m pip install --upgrade pip
-      #     pip install awsebcli
+      
+      - name: Install EB CLI using pip
+        run: |
+          python -m pip install --upgrade pip
+          pip install awsebcli
 
-      # - name: Initialize EB CLI
-      #   run: |
-      #     eb init ${{ env.AWS_EBS_APPLICATION }} --region ${{ env.AWS_DEFAULT_REGION }} --platform ${{ env.AWS_EBS_PLATFORM }}
-      #     eb use ${{ env.AWS_EBS_ENVIRONMENT }}
+      - name: Initialize EB CLI
+        run: |
+          eb init ${{ env.AWS_EBS_APPLICATION }} --region ${{ env.AWS_DEFAULT_REGION }} --platform ${{ env.AWS_EBS_PLATFORM }}
+          eb use ${{ env.AWS_EBS_ENVIRONMENT }}
+
+      - name: Get Elastic Beanstalk blue environment name
+        id: target-blue-env
+        env:
+          CNAME: ${{ env.AWS_DEFAULT_REGION }}
+        run: |
+          for ebs_env in $(eb list | awk '{print $1}'); do
+            echo "$ebs_env"
+            ebs_env_cname=$(eb status $ebs_env | grep "CNAME:" | awk '{print $2}')
+            [ "$ebs_env_cname" = "$CNAME" ] && blue_env_name="$ebs_env" >> $GITHUB_OUTPUT
+          done
+
+          [ -z "$blue_env_name" ] && { echo "Elastic beanstalk blue environment not found"; exit 1; }
 
       # - name: Elastic Beanstalk Health Check
       #   run: |
