Update cd.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -33,34 +33,50 @@ jobs:
           prefix: null
           decryption: true
           
-      - name: Output Bardavon Actions
-        run: echo $STAGING_ENV
+      # - name: Output Bardavon Actions
+      #   run: echo $STAGING_ENV
         
-      - name: Parse and set environment variables
-        run: |
-          echo "${{ env.API_KEYS_JSON }}" > keys.json
-          envs=$(jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | join("\n")' keys.json)
-          echo "$envs" >> $GITHUB_ENV
+      # - name: Parse and set environment variables
+      #   run: |
+      #     echo "${{ env.API_KEYS_JSON }}" > keys.json
+      #     envs=$(jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | join("\n")' keys.json)
+      #     echo "$envs" >> $GITHUB_ENV
 
-      - name: Create .env file
-        id: create-env
-        uses: SpicyPizza/create-envfile@v2.0
-        with:
-          envkey_API_KEYS_JSON: ${{ env.API_KEYS_JSON }}
-          envkey_API_KEYS: ${{ toJSON(env.API_KEYS_JSON) }}
-          envkey_SANDBOX_MODE: false
-          envkey_DEMO_MODE: false
-          envkey_PLAYGROUND: false
-          envkey_API_DOCS_PATH: /docs
-          fail_on_empty: true
+      # - name: Create .env file
+      #   id: create-env
+      #   uses: SpicyPizza/create-envfile@v2.0
+      #   with:
+      #     envkey_API_KEYS_JSON: ${{ env.API_KEYS_JSON }}
+      #     envkey_API_KEYS: ${{ toJSON(env.API_KEYS_JSON) }}
+      #     envkey_SANDBOX_MODE: false
+      #     envkey_DEMO_MODE: false
+      #     envkey_PLAYGROUND: false
+      #     envkey_API_DOCS_PATH: /docs
+      #     fail_on_empty: true
           
-      - name: Read .env file contents
-        run: |
-          echo "Contents of .env file:"
-          cat .env
+      # - name: Read .env file contents
+      #   run: |
+      #     echo "Contents of .env file:"
+      #     cat .env
 
-      - name: Save .env file as artifact
-        uses: actions/upload-artifact@v2
-        with:
-          name: env-file
-          path: .env
+      # - name: Save .env file as artifact
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: env-file
+      #     path: .env
+      - name: Retry Step
+        id: retry
+        run: |
+          for attempt in 1 2; do
+            eb health ${{ env.AWS_EBS_ENVIRONMENT }} | awk 'NR>2 && $2 == "ok" {getline; if ($2 == 0) {exit_status=1}} END {exit exit_status}'
+            exit_status=$?
+            if [ $exit_status -eq 0 ]; then
+              # Exit if the command succeeds
+              exit 0
+            fi
+            if [ $attempt -lt 2 ]; then
+              echo "Retrying in 1 minute and 30 seconds..."
+              sleep 90
+            fi
+          done
+          exit 1
