Update cd.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -112,10 +112,25 @@ jobs:
           eb init ${{ env.AWS_EBS_APPLICATION }} --region ${{ env.AWS_DEFAULT_REGION }} --platform ${{ env.AWS_EBS_PLATFORM }}
 
       - name: Get Elastic Beanstalk blue environment name
-        if: ${{ inputs.app-name != 'merchant-portal' }}
+        id: target-blue-env
+        shell: bash
         run: |
-          eb list --all > eb_list_output.txt
-          cat eb_list_output.txt
+          ebs_envs=$(eb list --all | awk '{if ($1 == "*") print $2; else print $1}')
+          echo "$ebs_envs"
+          for ebs_env in $ebs_envs; do
+            ebs_env_cname=$(eb status $ebs_env | grep "CNAME:" | awk '{print $2}')
+            echo "$ebs_env_cname"
+            [ "$ebs_env_cname" = 'staging-5.ap-southeast-1.elasticbeanstalk.com' ] && blue_env_name="$ebs_env"
+          done
+
+          echo "$blue_env_name"
+          echo "blue_env_name=$blue_env_name" >> $GITHUB_OUTPUT
+          if [ -n "$blue_env_name" ]; then
+            echo "Blue environment found: $blue_env_name"
+          else
+            echo "Elastic Beanstalk blue environment for: not found"
+            exit 1
+          fi
 
       # - name: Initialize EB CLI
       #   run: |
